title: Schuchert Wikispaces
description: Port of schuchert.wikispaces.com
twitter_username: schuchert
theme: jekyll-theme-midnight
highlight: rogue
github_username: schuchert
layout: kramdown
makrdown: kramdown
kramdown: 
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
blog: "https://schuchert.github.io"
url: "https://schuchert.github.io/wikispaces"
repository: schuchert/wikispaces
baseurl: /wikispaces
github: [metadata]
exclude: [.idea,site_errors,bin,_build,.gitignore,.gitconfig,Gemfile,Gemfile.lock]
include: [favico.ico]
